[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && cp package-server.json package.json && npm install"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
