[build]
builder = "nixpacks"
buildCommand = "cp package-server.json package.json && npm install --legacy-peer-deps"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
